### ISSUE TITLE
output of pygargl.py

### ISSUE THREAD

**Issue by upasna2** [KarolTx/pygargl#1]
Hi , 
I was trying to compile the pygargl.py file with the sample yahoosearch.gtf and I cannot understand the output. The output looks like :
[{'searchResultTitles': [<Element a at 0x7fcb636d12c8>, <Element a at 0x7fcb636d1318>, <Element a at 0x7fcb636d1368>, <Element a at 0x7fcb636d1458>, <Element a at 0x7fcb636d14a8>, <Element a at 0x7fcb636d14f8>, <Element a at 0x7fcb636d1548>, <Element a at 0x7fcb636d1598>, <Element a at 0x7fcb636d15e8>, <Element a at 0x7fcb636d1638>]}, {'suggestions': [<Element td at 0x7fcb66786f98>, <Element td at 0x7fcb636d1688>, <Element td at 0x7fcb636d16d8>, <Element td at 0x7fcb636d1728>, <Element td at 0x7fcb636d1778>, <Element td at 0x7fcb636d17c8>, <Element td at 0x7fcb636d1818>, <Element td at 0x7fcb636d11d8>]}].

Also when I run it with other gtf files , I get different errors. Please Help!

**Comment by KarolTx** [comment]
Hi, could you post the code you used?
When you run `python pygargl.py` it just executes the following code:

```
ARG_GTF = 'sample/yahoosearch.gtf'
g = gargl(ARG_GTF)
print(g.Search({'query': 'python'}))
print(g.Search({'query': 'pygargl'}))
```

So I run it myself and got:

```
$ git clone https://github.com/KarolTx/pygargl/
Cloning into 'pygargl'...
remote: Counting objects: 36, done.
remote: Total 36 (delta 0), reused 0 (delta 0), pack-reused 36
Unpacking objects: 100% (36/36), done.
Checking connectivity... done.
$ cd pygargl
$ python3 pygargl.py
[{'searchResultTitles': [<Element a at 0x7f4c39296188>, <Element a at 0x7f4c392961d8>, <Element a at 0x7f4c39296278>, <Element a at 0x7f4c392962c8>, <Element a at 0x7f4c39296318>, <Element a at 0x7f4c39296368>, <Element a at 0x7f4c392963b8>, <Element a at 0x7f4c39296408>, <Element a at 0x7f4c39296458>, <Element a at 0x7f4c392964a8>, <Element a at 0x7f4c392964f8>, <Element a at 0x7f4c39296548>, <Element a at 0x7f4c39296598>, <Element a at 0x7f4c392965e8>, <Element a at 0x7f4c39296638>, <Element a at 0x7f4c39296688>, <Element a at 0x7f4c392966d8>, <Element a at 0x7f4c39296728>, <Element a at 0x7f4c39296778>]}, {'suggestions': [<Element td at 0x7f4c39296228>, <Element td at 0x7f4c392967c8>, <Element td at 0x7f4c39296818>, <Element td at 0x7f4c39296868>, <Element td at 0x7f4c392968b8>, <Element td at 0x7f4c39296908>, <Element td at 0x7f4c39296958>, <Element td at 0x7f4c392969a8>]}]
[{'searchResultTitles': [<Element a at 0x7f4c3995d368>, <Element a at 0x7f4c39296188>, <Element a at 0x7f4c392961d8>, <Element a at 0x7f4c39296278>, <Element a at 0x7f4c39296408>, <Element a at 0x7f4c392962c8>, <Element a at 0x7f4c39296458>, <Element a at 0x7f4c392964a8>, <Element a at 0x7f4c39296548>, <Element a at 0x7f4c392964f8>, <Element a at 0x7f4c39296598>, <Element a at 0x7f4c392965e8>, <Element a at 0x7f4c39296638>, <Element a at 0x7f4c39296728>]}, {'suggestions': []}]
```

=> There are some python-lxml objects printed out.

**Comment by upgradeQ** [comment]
@KarolTx is there any hacks to make it **raw text**?  lxml module a little _fuzzy_ , there is should be a way to make content a non-lxml object

**Comment by upgradeQ** [comment]
to see raw content , you need to `
foo = g.Search({'query': "something"})[0]
print(etree.tostring(foo["query"][0],pretty_print=True))`
and use number of slice to see form data

**Comment by KarolTx** [comment]
Let's consider following element is the end result of your query:
`<p>Lorem ipsum <span class="bold">dolor</span> sit amet</p>`

@HQupgradeHQ what is the expected text output?
1. Lorem ipsum <span class="bold">dolor</span> sit amet
2. Lorem ipsum dolor sit amet
3. Lorem ipsum sit amet
4. maybe something else?

Now consider a table with a lot of cells and data, no whitespaces between the cell definitions (`<td>one</td><td>another</td>`). What should be the default behaviour?

I am not sure. I am open for suggestions or PRs :)

**Comment by upgradeQ** [comment]
> @HQupgradeHQ what is the expected text output? 
1. Lorem ipsum dolor sit amet . But it depends... 
Now about a table: lxml object is pretty suitable here, and [this](http://lxml.de/) site helps a lot.

**Comment by KarolTx** [comment]
> @HQupgradeHQ: Lorem ipsum dolor sit amet . But it depends...

From my own usage, the necessary output is a list of all lxml objects to process further. :)
Maybe some decorators or another way to parse the objects would be useful. At this moment I will let it stay the same.
